"""make_chapter_fields_nullable_add_status

Revision ID: 081d0c8f4d27
Revises: 5495e5ef0b76
Create Date: 2026-02-15 22:54:52.094884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '081d0c8f4d27'
down_revision: Union[str, Sequence[str], None] = '5495e5ef0b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('chapters', 'title',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('chapters', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chapters', 'paragraphs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chapters', 'paragraphs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('chapters', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chapters', 'title',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('chapters', 'status')
    # ### end Alembic commands ###
