"""add introduce to book and summary to chapter

Revision ID: 4e653d04efe0
Revises: db07e12c6486
Create Date: 2026-02-15 09:44:32.058865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4e653d04efe0'
down_revision: Union[str, Sequence[str], None] = 'db07e12c6486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('introduce', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('chapters', sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'summary')
    op.drop_column('books', 'introduce')
    # ### end Alembic commands ###
